CREATE DATABASE BD_PRACTICA_CAPAS
GO

USE BD_PRACTICA_CAPAS
GO

--drop database  BD_PRACTICA_CAPAS

CREATE TABLE CLIENTES(
	ID_CLIENTE int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOMBRE varchar(80) NOT NULL,
	TELEFONO varchar(11) NULL,
	DIRECCION varchar(80) NULL,
)


CREATE TABLE PRODUCTOS(
	ID_PRODUCTO int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DESCRIPCION varchar(80) NOT NULL,
	PRECIOCOMPRA decimal(10,2) NOT NULL,
	PRECIOVENTA decimal(10,2) NOT NULL,
	GRAVADO CHAR NOT NULL DEFAULT 0
)

CREATE TABLE ENCABEZADO_FACTURA(
	ID_FACTURA int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	FECHA DATETIME DEFAULT GETDATE(),
	ID_CLIENTE int NOT NULL,
	SUBTOTAL decimal(10,2) NOT NULL,
	IMPUESTO decimal(10,2) NOT NULL,
	MONTODESCUENTO decimal(10,2) NOT NULL
)

CREATE TABLE DETALLE_FACTURA(
	ID_FACTURA int NOT NULL,
	ID_PRODUCTO int NOT NULL,
	CANTIDAD INT,
	CONSTRAINT PK_DETALLE_FACTURA PRIMARY KEY (ID_FACTURA,ID_PRODUCTO)
)

ALTER TABLE ENCABEZADO_FACTURA ADD CONSTRAINT FK_ENCABEZADO_FACTURA
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)

ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT FK_DETALLE_FACTURA
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)

ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT FK_DETALLE_FACTURA_ENCABEZADO
FOREIGN KEY (ID_FACTURA) REFERENCES ENCABEZADO_FACTURA(ID_FACTURA)



INSERT INTO CLIENTES(NOMBRE, TELEFONO, DIRECCION)
VALUES	('Alejandra Alfaro Arias', '88-88-88-01', 'San José'), 
		('Brenda Brenes Bonilla', '88-88-88-02', 'Heredia'), 
		('Carlos Contreras Castro', '88-88-88-03', 'Cartago'), 
		('Daniel Días Durán', '88-88-88-04', 'Alajuela'); 

Select * from clientes


INSERT INTO PRODUCTOS(DESCRIPCION, PRECIOCOMPRA, PRECIOVENTA)
VALUES	('Arroz',1000,1200), 
		('Frijoles',800,1000), 
		('Garbanzos',650,850), 
		('Masa',700,900),
		('Harina',1500,1700), 
		('Sal',200,400), 
		('Azúcar',990,1100), 
		('Spaguetti',750,950),
		('Leche',800,1000), 
		('Chocolate',675,875), 
		('Queso Crema',1100,1300);

Select * from productos

--inserte 4 clientes, 10 productos, 10 encabezados de factura y  de 3 a 5 registros en detalles de factura para cada factura, utilizando sintaxis SQL. 


INSERT INTO ENCABEZADO_FACTURA(ID_CLIENTE,SUBTOTAL,IMPUESTO,MONTODESCUENTO)
VALUES	(1,1200,13,0), 
		(2,1000,13,0), 
		(2,850,13,0), 
		(4,900,13,0),
		(1,1700,13,0), 
		(2,400,13,0), 
		(4,1100,13,0), 
		(4,950,13,0),
		(1,1000,13,0), 
		(1,875,13,0);


		
INSERT INTO DETALLE_FACTURA(ID_FACTURA,ID_PRODUCTO, CANTIDAD)
VALUES	(1,1,1), 
		(2,2,2), 
		(3,3,1);
		
INSERT INTO DETALLE_FACTURA(ID_FACTURA,ID_PRODUCTO, CANTIDAD)
VALUES	(4,4,1), 
		(5,5,2), 
		(6,6,3);
			
INSERT INTO DETALLE_FACTURA(ID_FACTURA,ID_PRODUCTO, CANTIDAD)
VALUES	(7,7,1), 
		(8,8,2), 
		(9,9,1),
		(10,10,1);


		SELECT * FROM DETALLE_FACTURA
		SELECT * FROM ENCABEZADO_FACTURA


CREATE PROCEDURE ELIMINAR
		@idcliente int,  --recibe un id
		@msj varchar(50) out   --devuelve un mensaje
AS BEGIN
if (not exists(select * from CLIENTES where ID_CLIENTE=@idcliente))
	begin
		set @msj='El cliente no existe'
		return 0
	end
else
	begin
		DELETE from CLIENTES where ID_CLIENTE=@idcliente
		set @msj='Cliente eliminado'
		return 1
	end
END
GO

